### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [amperka/I2CioExpander#5]
In the file "src/GpioExpander.cpp", there is waiting after a Wire.requestFrom(). You may remove that.
I wrote a possible fix at the other repository: https://github.com/amperka/Octoliner/issues/6
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by yurybotov** [comment]
Done

**Comment by Koepel** [comment]
One more in the function GpioExpander::read32bit(). I suggest to make it the same as in the Octoliner repository.
